### ISSUE TITLE
File extracts

### ISSUE THREAD

**Issue by sourcx** [trapmine/zeek-amqp#1]
Hi, 

Cool project! 

Is it also possible to send file extracts to RabbitMQ as well? 

Cheers
sourcx

**Comment by msaboor35** [comment]
Hi.

You probably will not be able to send extracted files using this plugin. In zeek, you add the ANALYZER_EXTRACT analyzer to the file you want to extract but I do not think it is possible to access the file's contents through the framework. After adding the analyzer, maybe you can send this file through the rabbitmqadmin command in the file_remove event.

**Comment by sourcx** [comment]
I see, thanks for the extra information! I'll see if I can get something to work within the scripting framework 👍🏻
